[tool.black]
line-length = 150
target-version = ["py39"]

[tool.ruff]
line-length = 150
target-version = "py39"
extend-exclude = [
  "build",
  "dist",
  "inx",
  "locales",
  "*-metadata.py",
  "pystitch-format-descriptions.py",
]

[tool.ruff.lint]
select = ["E9", "F63", "F7", "F82"]
